"""remove unique constrain from Meals table

Revision ID: 25a4a20e884d
Revises: d69ff1b6ac78
Create Date: 2024-03-22 12:49:56.628274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a4a20e884d'
down_revision = 'd69ff1b6ac78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_customer_reviews", 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint("fk_customer_reviews", type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
