"""empty message

Revision ID: 60098ded38dc
Revises: 87fb18d6c5ca
Create Date: 2024-04-09 11:43:37.563546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60098ded38dc'
down_revision = '87fb18d6c5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
