"""added foreignkey Customer to restaurant

Revision ID: 95ed9ad7d4f6
Revises: 25a4a20e884d
Create Date: 2024-03-25 11:35:21.016750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ed9ad7d4f6'
down_revision = '25a4a20e884d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_customer_restaurant', 'restaurants', ['resto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customer_restaurant', type_='foreignkey')
        batch_op.drop_column('resto_id')

    # ### end Alembic commands ###
